---

- hosts: all
  gather_facts: false
  remote_user: root
  tasks:
#    - name: Update
#      apt:
#        name: "*"
#        state: latest

    - name: Ensure python is available
      apt:
        name: python-minimal
        allow_unauthenticated: yes

    - name: Ensure python-apt is available
      apt:
        name: python-apt
        allow_unauthenticated: yes

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

- hosts: debrepo

  tasks:
    - user: name=reprepro group=wwwdata

# This should not be needed, but I am getting 'root:root' as owner of the /home/reprepro directory
  - name: Ensure HOME directory exists with right permissions
    file: dest=/home/reprepro state=directory mode=0755 owner="{{ gpg_generator_user }}"

  roles:
    - role: generate_gpgkey
      gpg_generator_user: 'reprepro'
      gpg_user: 'reprepro'
      gpg_realname: 'reprepro'
      gpg_useremail: 'reprepro@localhost'
      gpg_pubkeyfile: 'debrepo.pub'
      gpg_privkeyfile: 'debrepo.priv'

  tasks:
    - name: Export PGP key
      become: yes
      become_user: reprepro
      raw: gpg --armor --export reprepro@localhost --output $HOME/reprepro@localhost.gpg.key

    - file: path=/etc/debian-repository state=directory mode=775 owner=wwwdata group=wwwdata
    - file: path=/var/reprepro/incoming/dev state=directory mode=775 owner=wwwdata group=wwwdata
    - file: path=/var/reprepro/incoming/staging state=directory mode=775 owner=wwwdata group=wwwdata
    - file: path=/var/reprepro/incoming/prod state=directory mode=775 owner=wwwdata group=wwwdata

    - name: Copy cron job
      template: src=cronjob.sh.j2 dest=/var/reprepro/bin/cronjob.sh mode=775 owner=wwwdata group=wwwdata

    - name: Install Apache web server
      apt:
        name: apache2
        state: latest

    - name: Copy Apache configuration
      template: src=reprepro.conf.j2 dest=/etc/apache2/sites-available/debrepo.conf mode=775 owner=wwwdata group=wwwdata

    - name: Install reprepro
      apt:
        name: reprepro
        state: latest

    - name: Install cron job
      become: yes
      become_user: reprepro
      cron:
        name: "Update Debian Repository"
        minute: "*/10"
        job: "/var/reprepro/bin/cronjob.sh"
